export const FETCH_CLAIM_TYPES = '@claimType/FETCH_CLAIM_TYPES';
export const FETCH_CLAIM_TYPES_START = '@claimType/FETCH_CLAIM_TYPES_START';
export const FETCH_CLAIM_TYPES_SUCCESS = '@claimType/FETCH_CLAIM_TYPES_SUCCESS';
export const FETCH_CLAIM_TYPES_ERROR = '@claimType/FETCH_CLAIM_TYPES_ERROR';
