/* istanbul ignore file */

const PREFIX = '@@shop';

export const GET_DELIVERY_ADDRESSES = `${PREFIX}/GET_DELIVERY_ADDRESSES`;
export const GET_DELIVERY_ADDRESSES_START = `${PREFIX}/GET_DELIVERY_ADDRESSES_START`;
export const GET_DELIVERY_ADDRESSES_SUCCESS = `${PREFIX}/GET_DELIVERY_ADDRESSES_SUCCESS`;
export const GET_DELIVERY_ADDRESSES_ERROR = `${PREFIX}/GET_DELIVERY_ADDRESSES_ERROR`;

export const ADD_DELIVERY_ADDRESS = `${PREFIX}/ADD_DELIVERY_ADDRESS`;
export const ADD_DELIVERY_ADDRESS_START = `${PREFIX}/ADD_DELIVERY_ADDRESS_START`;
export const ADD_DELIVERY_ADDRESS_SUCCESS = `${PREFIX}/ADD_DELIVERY_ADDRESS_SUCCESS`;
export const ADD_DELIVERY_ADDRESS_ERROR = `${PREFIX}/ADD_DELIVERY_ADDRESS_ERROR`;

export const UPDATE_DELIVERY_ADDRESS = `${PREFIX}/UPDATE_DELIVERY_ADDRESS`;
export const UPDATE_DELIVERY_ADDRESS_START = `${PREFIX}/UPDATE_DELIVERY_ADDRESS_START`;
export const UPDATE_DELIVERY_ADDRESS_SUCCESS = `${PREFIX}/UPDATE_DELIVERY_ADDRESS_SUCCESS`;
export const UPDATE_DELIVERY_ADDRESS_ERROR = `${PREFIX}/UPDATE_DELIVERY_ADDRESS_ERROR`;

export const DELETE_DELIVERY_ADDRESS = `${PREFIX}/DELETE_DELIVERY_ADDRESS`;
export const DELETE_DELIVERY_ADDRESS_START = `${PREFIX}/DELETE_DELIVERY_ADDRESS_START`;
export const DELETE_DELIVERY_ADDRESS_SUCCESS = `${PREFIX}/DELETE_DELIVERY_ADDRESS_SUCCESS`;
export const DELETE_DELIVERY_ADDRESS_ERROR = `${PREFIX}/DELETE_DELIVERY_ADDRESS_ERROR`;
