module.exports = {
  preset: 'react-native',
  setupFiles: ['./jest.setup.js'],
  setupFilesAfterEnv: ['./jest.timeoutconfig.js'],
  moduleNameMapper: {
    '@messages/(.*)': '<rootDir>/messages/$1',
  },
  notify: true,
  notifyMode: 'failure',
  moduleFileExtensions: ['js', 'jsx', 'json'],
  collectCoverage: true,
  collectCoverageFrom: [
    'src/**/*.{js,jsx}',
    '!**/src/config/**',
    '!**/src/navigations/**',
    '!**/src/middlewares/index.js',
    '!**/src/middlewares/applyMiddleware.js',
    '!**/src/store/configureStore.js',
    '!**/src/store/reducers.js',
    '!**/src/getAppNavigator.js',
    '!**/src/init.js',
    '!**/src/index.*',
    '!**/src/theme.*',
    '!**/src/routes.js',
    '!**/src/**/*.dev.{js,jsx}',
    '!**/src/components/App.js',
  ],
  coveragePathIgnorePatterns: [
    '<rootDir>/src/components/shops/',
    '<rootDir>/src/components/heal/',
  ],
  testPathIgnorePatterns: [
    '<rootDir>/src/components/shops/',
    '<rootDir>/node_modules/',
  ],
  coverageThreshold: {
    global: {
      branches: 85,
      functions: 90,
      lines: 94,
    },
  },
  transformIgnorePatterns: ['<rootDir>/node_modules/@react-native-firebase/'],
  coverageDirectory: '<rootDir>/coverage',
  testURL: 'http://localhost',
  verbose: true,
};
