/* istanbul ignore file */

const PREFIX = '@@shop';

export const GET_STORE_CONFIGS = `${PREFIX}/GET_STORE_CONFIGS`;
export const GET_STORE_CONFIGS_START = `${PREFIX}/GET_STORE_CONFIGS_START`;
export const GET_STORE_CONFIGS_SUCCESS = `${PREFIX}/GET_STORE_CONFIGS_SUCCESS`;
export const GET_STORE_CONFIGS_ERROR = `${PREFIX}/GET_STORE_CONFIGS_ERROR`;

export const GET_CATEGORIES = `${PREFIX}/GET_CATEGORIES`;
export const GET_CATEGORIES_START = `${PREFIX}/GET_CATEGORIES_START`;
export const GET_CATEGORIES_SUCCESS = `${PREFIX}/GET_CATEGORIES_SUCCESS`;
export const GET_CATEGORIES_ERROR = `${PREFIX}/GET_CATEGORIES_ERROR`;

export const GET_SORTINGS = `${PREFIX}/GET_SORTINGS`;
export const GET_SORTINGS_START = `${PREFIX}/GET_SORTINGS_START`;
export const GET_SORTINGS_SUCCESS = `${PREFIX}/GET_SORTINGS_SUCCESS`;
export const GET_SORTINGS_ERROR = `${PREFIX}/GET_SORTINGS_ERROR`;

export const GET_COUNTRIES = `${PREFIX}/GET_COUNTRIES`;
export const GET_COUNTRIES_START = `${PREFIX}/GET_COUNTRIES_START`;
export const GET_COUNTRIES_SUCCESS = `${PREFIX}/GET_COUNTRIES_SUCCESS`;
export const GET_COUNTRIES_ERROR = `${PREFIX}/GET_COUNTRIES_ERROR`;
