export const FETCH_TERMS_CONDITIONS = '@legal/FETCH_TERMS_CONDITIONS';
export const FETCH_TERMS_CONDITIONS_START =
  '@legal/FETCH_TERMS_CONDITIONS_START';
export const FETCH_TERMS_CONDITIONS_SUCCESS =
  '@legal/FETCH_TERMS_CONDITIONS_SUCCESS';
export const FETCH_TERMS_CONDITIONS_ERROR =
  '@legal/FETCH_TERMS_CONDITIONS_ERROR';

export const FETCH_PRIVACY_POLICY = '@legal/FETCH_PRIVACY_POLICY';
export const FETCH_PRIVACY_POLICY_START = '@legal/FETCH_PRIVACY_POLICY_START';
export const FETCH_PRIVACY_POLICY_SUCCESS =
  '@legal/FETCH_PRIVACY_POLICY_SUCCESS';
export const FETCH_PRIVACY_POLICY_ERROR = '@legal/FETCH_PRIVACY_POLICY_ERROR';

export const FETCH_MYWELLNESS_NEWSLETTER = '@legal/FETCH_MYWELLNESS_NEWSLETTER';
export const FETCH_MYWELLNESS_NEWSLETTER_START =
  '@legal/FETCH_MYWELLNESS_NEWSLETTER_START';
export const FETCH_MYWELLNESS_NEWSLETTER_SUCCESS =
  '@legal/FETCH_MYWELLNESS_NEWSLETTER_SUCCESS';
export const FETCH_MYWELLNESS_NEWSLETTER_ERROR =
  '@legal/FETCH_MYWELLNESS_NEWSLETTER_ERROR';
