const PREFIX = '@@shop';

export const GET_ORDER_HISTORY = `${PREFIX}/GET_ORDER_HISTORY`;
export const GET_ORDER_HISTORY_START = `${PREFIX}/GET_ORDER_HISTORY_START`;
export const GET_ORDER_HISTORY_SUCCESS = `${PREFIX}/GET_ORDER_HISTORY_SUCCESS`;
export const GET_ORDER_HISTORY_ERROR = `${PREFIX}/GET_ORDER_HISTORY_ERROR`;

export const GET_ORDER_DETAIL = `${PREFIX}/GET_ORDER_DETAIL`;
export const GET_ORDER_DETAIL_START = `${PREFIX}/GET_ORDER_DETAIL_START`;
export const GET_ORDER_DETAIL_SUCCESS = `${PREFIX}/GET_ORDER_DETAIL_SUCCESS`;
export const GET_ORDER_DETAIL_ERROR = `${PREFIX}/GET_ORDER_DETAIL_ERROR`;


export const GET_TRACK_ORDER = `${PREFIX}/GET_TRACK_ORDER`;
export const GET_TRACK_ORDER_START = `${PREFIX}/GET_TRACK_ORDER_START`;
export const GET_TRACK_ORDER_SUCCESS = `${PREFIX}/GET_TRACK_ORDER_SUCCESS`;
export const GET_TRACK_ORDER_ERROR = `${PREFIX}/GET_TRACK_ORDER_ERROR`;
