export const FETCH_BENEFITS = '@benefit/FETCH_BENEFITS';
export const FETCH_BENEFITS_START = '@benefit/FETCH_BENEFITS_START';
export const FETCH_BENEFITS_SUCCESS = '@benefit/FETCH_BENEFITS_SUCCESS';
export const FETCH_BENEFITS_ERROR = '@benefit/FETCH_BENEFITS_ERROR';

export const FETCH_BENEFIT_DOCUMENTS = '@benefit/FETCH_BENEFIT_DOCUMENTS';
export const FETCH_BENEFIT_DOCUMENTS_START =
  '@benefit/FETCH_BENEFIT_DOCUMENTS_START';
export const FETCH_BENEFIT_DOCUMENTS_SUCCESS =
  '@benefit/FETCH_BENEFIT_DOCUMENTS_SUCCESS';
export const FETCH_BENEFIT_DOCUMENTS_ERROR =
  '@benefit/FETCH_BENEFIT_DOCUMENTS_ERROR';

export const FETCH_POLICY_DETAILS = '@benefit/FETCH_POLICY_DETAILS';
export const FETCH_POLICY_DETAILS_START = '@benefit/FETCH_POLICY_DETAILS_START';
export const FETCH_POLICY_DETAILS_SUCCESS =
  '@benefit/FETCH_POLICY_DETAILS_SUCCESS';
export const FETCH_POLICY_DETAILS_ERROR = '@benefit/FETCH_POLICY_DETAILS_ERROR';

export const FETCH_HEALTHCARDS = '@benefit/FETCH_HEALTHCARDS';
export const FETCH_HEALTHCARDS_START = '@benefit/FETCH_HEALTHCARDS_START';
export const FETCH_HEALTHCARDS_SUCCESS = '@benefit/FETCH_HEALTHCARDS_SUCCESS';
export const FETCH_HEALTHCARDS_ERROR = '@benefit/FETCH_HEALTHCARDS_ERROR';
