const PREFIX = `@@heal`;
export const GET_DOCTORS = `${PREFIX}/GET_DOCTORS`;
export const GET_DOCTORS_SUCCESS = `${PREFIX}/GET_DOCTORS_SUCCESS`;
export const GET_DOCTORS_ERROR = `${PREFIX}/GET_DOCTORS_ERROR`;

export const GET_DOCTOR_DETAIL = `${PREFIX}/GET_DOCTOR_DETAIL`;
export const GET_DOCTOR_DETAIL_SUCCESS = `${PREFIX}/GET_DOCTOR_DETAIL_SUCCESS`;
export const GET_DOCTOR_DETAIL_ERROR = `${PREFIX}/GET_DOCTOR_DETAIL_ERROR`;

export const FETCH_LOCATION = `${PREFIX}/FETCH_LOCATION`;
export const FETCH_LOCATION_START = `${PREFIX}/FETCH_LOCATION_START`;
export const FETCH_LOCATION_SUCCESS = `${PREFIX}/FETCH_LOCATION_SUCCESS`;
export const FETCH_LOCATION_ERROR = `${PREFIX}/FETCH_LOCATION_ERORR`;

export const FETCH_CLINICS = `${PREFIX}/FETCH_CLINICS`;
export const FETCH_CLINICS_START = `${PREFIX}/FETCH_CLINICS_START`;
export const FETCH_CLINICS_SUCCESS = `${PREFIX}/FETCH_CLINICS_SUCCESS`;
export const FETCH_CLINICS_ERROR = `${PREFIX}/FETCH_CLINICS_ERROR`;

export const GET_SPECIALITIES = `${PREFIX}/GET_SPECIALITIES`;
export const GET_SPECIALITIES_START = `${PREFIX}/GET_SPECIALITIES_START`;
export const GET_SPECIALITIES_SUCCESS = `${PREFIX}/GET_SPECIALITIES_SUCCESS`;
export const GET_SPECIALITIES_ERROR = `${PREFIX}/GET_SPECIALITIES_ERROR`;

export const GET_DOCTORS_INFO = `${PREFIX}/GET_DOCTORS_INFO`;
export const GET_DOCTORS_INFO_START = `${PREFIX}/GET_DOCTORS_INFO_START`;
export const GET_DOCTORS_INFO_SUCCESS = `${PREFIX}/GET_DOCTORS_INFO_SUCCESS`;

export const SET_DETAILS_CLINIC = `${PREFIX}/SET_DETAILS_CLINIC`;

export const SEARCH = `${PREFIX}/SEARCH`;
export const SEARCH_SUCCESS = `${PREFIX}/SEARCH_SUCCESS`;
export const SEARCH_ERROR = `${PREFIX}/SEARCH_ERROR`;
export const CLEAR_SEARCH = `${PREFIX}/CLEAR_SEARCH`;

export const SCAN_QR_CODE = `${PREFIX}/SCAN_QR_CODE`;
export const SCAN_QR_CODE_START = `${PREFIX}/SCAN_QR_CODE_START`;
export const SCAN_QR_CODE_SUCCESS = `${PREFIX}/SCAN_QR_CODE_SUCCESS`;
export const SCAN_QR_CODE_ERROR = `${PREFIX}/SCAN_QR_CODE_ERROR`;

export const GET_MEDICAL_PROFILE = `${PREFIX}/GET_MEDICAL_PROFILE`;
export const GET_MEDICAL_PROFILE_SUCCESS = `${PREFIX}/GET_MEDICAL_PROFILE_SUCCESS`;
export const GET_MEDICAL_PROFILE_ERROR = `${PREFIX}/GET_MEDICAL_PROFILE_ERROR`;

export const UPDATE_MEDICAL_PROFILE = `${PREFIX}/UPDATE_MEDICAL_PROFILE`;
export const UPDATE_MEDICAL_PROFILE_SUCCESS = `${PREFIX}/UPDATE_MEDICAL_PROFILE_SUCCESS`;
export const UPDATE_MEDICAL_PROFILE_ERROR = `${PREFIX}/UPDATE_MEDICAL_PROFILE_ERROR`;

export const GET_MEMBER = `${PREFIX}/GET_MEMBER`;
export const GET_MEMBER_SUCCESS = `${PREFIX}/GET_MEMBER_SUCCESS`;
export const GET_MEMBER_ERROR = `${PREFIX}/GET_MEMBER_ERROR`;

export const REQUEST_APPOINTMENT = `${PREFIX}/REQUEST_APPOINTMENT`;
export const REQUEST_APPOINTMENT_SUCCESS = `${PREFIX}/REQUEST_APPOINTMENT_SUCCESS`;
export const REQUEST_APPOINTMENT_ERROR = `${PREFIX}/REQUEST_APPOINTMENT_ERROR`;

export const ClinicSearchType = {
  Name: 'clinic_name',
  Location: 'clinic_location',
};

export const DoctorSearchType = {
  Name: 'doctor_name',
};

export const SearchItemType = {
  Doctor: 'doctor',
  Clinic: 'clinic',
  Location: 'location',
  Speciality: 'speciality',
  Recent: 'recent',
  NearMe: '#nearme',
};

export const RECENT_SEARCH = 'RECENT_SEARCH';
export const UNIFY_SEARCH_DISTANCE = 5;
export const GET_ALL = 1000;

export const UPDATE_SELECTED_CLINIC = `${PREFIX}/UPDATE_SELECTED_CLINIC`;
export const UPDATE_SELECTED_CLINICS = `${PREFIX}/UPDATE_SELECTED_CLINICS`;
export const UPDATE_CLINIC_PAGE = `${PREFIX}/UPDATE_CLINIC_PAGE`;

export const CHECK_IN_WALK_IN = `${PREFIX}/CHECK_IN_WALK_IN`;
export const CHECK_IN_WALK_IN_START = `${PREFIX}/CHECK_IN_WALK_IN_START`;
export const CHECK_IN_WALK_IN_SUCCESS = `${PREFIX}/CHECK_IN_WALK_IN_SUCCESS`;
export const CHECK_IN_WALK_IN_ERROR = `${PREFIX}/CHECK_IN_WALK_IN_ERROR`;

export const GET_APPOINTMENT_LIST = `${PREFIX}/GET_APPOINTMENT_LIST`;
export const ACCEPT_APPOINTMENT = `${PREFIX}/ACCEPT_APPOINTMENT`;

export const GET_REMOTE_TICKETS = `${PREFIX}/GET_REMOTE_TICKETS`;
export const GET_REMOTE_TICKETS_SUCCESS = `${PREFIX}/GET_REMOTE_TICKETS_SUCCESS`;
export const GET_REMOTE_TICKETS_ERROR = `${PREFIX}/GET_REMOTE_TICKETS_ERROR`;
