const PREFIX = `@@user`;

export const LOGOUT = `${PREFIX}/LOGOUT`;

export const FORGOTPASSWORD = `${PREFIX}/FORGOTPASSWORD`;

export const LOGIN = `${PREFIX}/LOGIN`;
export const LOGIN_START = `${PREFIX}/LOGIN_START`;
export const LOGIN_SUCCESS = `${PREFIX}/LOGIN_SUCCESS`;
export const LOGIN_ERROR = `${PREFIX}/LOGIN_ERROR`;

export const UPDATE_LAST_LOGIN = `${PREFIX}/UPDATE_LAST_LOGIN`;
export const UPDATE_LAST_LOGIN_START = `${PREFIX}/UPDATE_LAST_LOGIN_START`;
export const UPDATE_LAST_LOGIN_SUCCESS = `${PREFIX}/UPDATE_LAST_LOGIN_SUCCESS`;
export const UPDATE_LAST_LOGIN_ERROR = `${PREFIX}/UPDATE_LAST_LOGIN_ERROR`;

export const GET_MEMBER_PROFILE = `${PREFIX}/GET_MEMBER_PROFILE`;
export const GET_MEMBER_PROFILE_START = `${PREFIX}/GET_MEMBER_PROFILE_START`;
export const GET_MEMBER_PROFILE_SUCCESS = `${PREFIX}/GET_MEMBER_PROFILE_SUCCESS`;
export const GET_MEMBER_PROFILE_ERROR = `${PREFIX}/GET_MEMBER_PROFILE_ERROR`;

export const GET_MEMBER_BALANCE = `${PREFIX}/GET_MEMBER_BALANCE`;
export const GET_MEMBER_BALANCE_START = `${PREFIX}/GET_MEMBER_BALANCE_START`;
export const GET_MEMBER_BALANCE_SUCCESS = `${PREFIX}/GET_MEMBER_BALANCE_SUCCESS`;
export const GET_MEMBER_BALANCE_ERROR = `${PREFIX}/GET_MEMBER_BALANCE_ERROR`;

export const UPDATE_MEMBER_PROFILE = `${PREFIX}/UPDATE_MEMBER_PROFILE`;
export const UPDATE_MEMBER_PROFILE_START = `${PREFIX}/UPDATE_MEMBER_PROFILE_START`;
export const UPDATE_MEMBER_PROFILE_SUCCESS = `${PREFIX}/UPDATE_MEMBER_PROFILE_SUCCESS`;
export const UPDATE_MEMBER_PROFILE_ERROR = `@${PREFIX}/UPDATE_MEMBER_PROFILE_ERROR`;

export const UPDATE_AGREEMENT_TERMS_CONDITIONS = `${PREFIX}/UPDATE_AGREEMENT_TERMS_CONDITIONS`;
export const UPDATE_AGREEMENT_TERMS_CONDITIONS_START = `${PREFIX}/UPDATE_AGREEMENT_TERMS_CONDITIONS_START`;
export const UPDATE_AGREEMENT_TERMS_CONDITIONS_SUCCESS = `${PREFIX}/UPDATE_AGREEMENT_TERMS_CONDITIONS_SUCCESS`;
export const UPDATE_AGREEMENT_TERMS_CONDITIONS_ERROR = `${PREFIX}/UPDATE_AGREEMENT_TERMS_CONDITIONS_ERROR`;

export const UPDATE_EDM_OPTED_OUT = `${PREFIX}/UPDATE_EDM_OPTED_OUT`;
export const UPDATE_EDM_OPTED_OUT_START = `${PREFIX}/UPDATE_EDM_OPTED_OUT_START`;
export const UPDATE_EDM_OPTED_OUT_SUCCESS = `${PREFIX}/UPDATE_EDM_OPTED_OUT_SUCCESS`;
export const UPDATE_EDM_OPTED_OUT_ERROR = `${PREFIX}/UPDATE_EDM_OPTED_OUT_ERROR`;

export const UPDATE_DEPENDENT_DATE_OF_BIRTH = `${PREFIX}/UPDATE_DEPENDENT_DATE_OF_BIRTH`;
export const UPDATE_DEPENDENT_DATE_OF_BIRTH_START = `${PREFIX}/UPDATE_DEPENDENT_DATE_OF_BIRTH_START`;
export const UPDATE_DEPENDENT_DATE_OF_BIRTH_SUCCESS = `${PREFIX}/UPDATE_DEPENDENT_DATE_OF_BIRTH_SUCCESS`;
export const UPDATE_DEPENDENT_DATE_OF_BIRTH_ERROR = `${PREFIX}/UPDATE_DEPENDENT_DATE_OF_BIRTH_ERROR`;

export const SEND_DEPENDENT_INVITE = `${PREFIX}/SEND_DEPENDENT_INVITE`;
export const SEND_DEPENDENT_INVITE_START = `${PREFIX}/SEND_DEPENDENT_INVITE_START`;
export const SEND_DEPENDENT_INVITE_SUCCESS = `${PREFIX}/SEND_DEPENDENT_INVITE_SUCCESS`;
export const SEND_DEPENDENT_INVITE_ERROR = `${PREFIX}/SEND_DEPENDENT_INVITE_ERROR`;

export const SELECT_DEPENDENT_INVITE = `${PREFIX}/SELECT_DEPENDENT_INVITE`;

export const REGISTER = `${PREFIX}/REGISTER`;
export const REGISTER_START = `${PREFIX}/REGISTER_START`;
export const REGISTER_SUCCESS = `${PREFIX}/REGISTER_SUCCESS`;
export const REGISTER_ERROR = `${PREFIX}/REGISTER_ERROR`;

export const RESEND_EMAIL = `${PREFIX}/RESEND_EMAIL`;
export const RESEND_EMAIL_SUCCESS = `${PREFIX}/RESEND_EMAIL_SUCCESS`;
export const RESEND_EMAIL_ERROR = `${PREFIX}/RESEND_EMAIL_ERROR`;
