const PREFIX = '@@shop';

export const ADD_TO_CART = `${PREFIX}/ADD_TO_CART`;
export const ADD_TO_CART_START = `${PREFIX}/ADD_TO_CART_START`;
export const ADD_TO_CART_SUCCESS = `${PREFIX}/ADD_TO_CART_SUCCESS`;
export const ADD_TO_CART_ERROR = `${PREFIX}/ADD_TO_CART_ERROR`;

export const GET_CART = `${PREFIX}/GET_CART`;
export const GET_CART_START = `${PREFIX}/GET_CART_START`;
export const GET_CART_SUCCESS = `${PREFIX}/GET_CART_SUCCESS`;
export const GET_CART_ERROR = `${PREFIX}/GET_CART_ERROR`;

export const GET_CART_TOTALS = `${PREFIX}/GET_CART_TOTALS`;
export const GET_CART_TOTALS_START = `${PREFIX}/GET_CART_TOTALS_START`;
export const GET_CART_TOTALS_SUCCESS = `${PREFIX}/GET_CART_TOTALS_SUCCESS`;
export const GET_CART_TOTALS_ERROR = `${PREFIX}/GET_CART_TOTALS_ERROR`;

export const GET_CART_BILLING = `${PREFIX}/GET_CART_BILLING`;
export const GET_CART_BILLING_START = `${PREFIX}/GET_CART_BILLING_START`;
export const GET_CART_BILLING_SUCCESS = `${PREFIX}/GET_CART_BILLING_SUCCESS`;
export const GET_CART_BILLING_ERROR = `${PREFIX}/GET_CART_BILLING_ERROR`;

export const GET_CART_SHIPPING = `${PREFIX}/GET_CART_SHIPPING`;
export const GET_CART_SHIPPING_START = `${PREFIX}/GET_CART_SHIPPING_START`;
export const GET_CART_SHIPPING_SUCCESS = `${PREFIX}/GET_CART_SHIPPING_SUCCESS`;
export const GET_CART_SHIPPING_ERROR = `${PREFIX}/GET_CART_SHIPPING_ERROR`;

export const REMOVE_ITEM_FROM_CART = `${PREFIX}/REMOVE_ITEM_FROM_CART`;
export const REMOVE_ITEM_FROM_CART_START = `${PREFIX}/REMOVE_ITEM_FROM_CART_START`;
export const REMOVE_ITEM_FROM_CART_SUCCESS = `${PREFIX}/REMOVE_ITEM_FROM_CART_SUCCESS`;
export const REMOVE_ITEM_FROM_CART_ERROR = `${PREFIX}/REMOVE_ITEM_FROM_CART_ERROR`;
