export const FETCH_DOCUMENTS = '@document/FETCH_DOCUMENTS';
export const FETCH_DOCUMENTS_START = '@document/FETCH_DOCUMENTS_START';
export const FETCH_DOCUMENTS_SUCCESS = '@document/FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_ERROR = '@document/FETCH_DOCUMENTS_ERROR';
