export const NAVIGATION_HOME_SCREEN_PATH = 'SHOP_HomeScreen';

export const NAVIGATION_HOME_PRODUCT_PATH = 'SHOP_Home_Product';

export const NAVIGATION_HOME_STACK_PATH = 'SHOP_Home';

export const SHOP_SELECT_CATEGORY_MODAL = 'SHOP_SELECT_CATEGORY_MODAL';
export const SHOP_SORT_MODAL = 'SHOP_SORT_SCREEN';
export const SHOP_FILTER_MODAL = 'SHOP_FILTER_SCREEN';

export const SHOP_CART_SCREEN = 'SHOP_CART_SCREEN';
export const SHOP_EDIT_PRODUCT_SCREEN = 'SHOP_EDIT_PRODUCT_SCREEN';
export const SHOP_REVIEW_SCREEN = 'SHOP_REVIEW_SCREEN';
export const SHOP_CHECKOUT_SCREEN = 'SHOP_CHECKOUT_SCREEN';

export const SHOP_DELIVERY_ADDRESSES_SCREEN = 'SHOP_DELIVERY_ADDRESSES_SCREEN';
export const SHOP_ADD_ADDRESS_SCREEN = 'SHOP_ADD_ADDRESS_SCREEN';
export const SHOP_EDIT_ADDRESS_SCREEN = 'SHOP_EDIT_ADDRESS_SCREEN';
export const SHOP_SINGLE_SELECT_MODAL = 'SHOP_SINGLE_SELECT_MODAL';

export const ORDER_HISTORY_SCREEN = 'ORDER_HISTORY_SCREEN';
export const ORDER_HISTORY_DETAIL_SCREEN = 'ORDER_HISTORY_DETAIL_SCREEN';
export const TRACK_ORDER_SCREEN = 'TRACK_ORDER_SCREEN';
export const WRITE_REVIEW_SCREEN = 'WRITE_REVIEW_SCREEN';
export const REVIEW_SUBMITTED_SCREEN = 'REVIEW_SUBMITTED_SCREEN';
