const PREFIX = '@@shop';

export const GET_REVIEW = `${PREFIX}/GET_REVIEW`;
export const GET_REVIEW_SUCCESS = `${PREFIX}/GET_REVIEW_SUCCESS`;
export const GET_REVIEW_ERROR = `${PREFIX}/GET_REVIEW_ERROR`;

export const GET_REVIEW_FORM = `${PREFIX}/GET_REVIEW_FORM`;
export const GET_REVIEW_FORM_SUCCESS = `${PREFIX}/GET_REVIEW_FORM_SUCCESS`;
export const GET_REVIEW_FORM_ERROR = `${PREFIX}/GET_REVIEW_FORM_ERROR`;

export const POST_REVIEW = `${PREFIX}/POST_REVIEW`;
export const POST_REVIEW_SUCCESS = `${PREFIX}/POST_REVIEW_SUCCESS`;
export const POST_REVIEW_ERROR = `${PREFIX}/POST_REVIEW_ERROR`;
