/* istanbul ignore file */

const PREFIX = '@@shop';

export const GET_SUGGESTED_PRODUCTS = `${PREFIX}/GET_SUGGESTED_PRODUCTS`;
export const GET_SUGGESTED_PRODUCTS_START = `${PREFIX}/GET_SUGGESTED_PRODUCTS_START`;
export const GET_SUGGESTED_PRODUCTS_SUCCESS = `${PREFIX}/GET_SUGGESTED_PRODUCTS_SUCCESS`;
export const GET_SUGGESTED_PRODUCTS_ERROR = `${PREFIX}/GET_SUGGESTED_PRODUCTS_ERROR`;

export const GET_PRODUCTS = `${PREFIX}/GET_PRODUCTS`;
export const GET_PRODUCTS_START = `${PREFIX}/GET_PRODUCTS_START`;
export const GET_PRODUCTS_SUCCESS = `${PREFIX}/GET_PRODUCTS_SUCCESS`;
export const GET_PRODUCTS_ERROR = `${PREFIX}/GET_PRODUCTS_ERROR`;

export const GET_PRODUCTS_BY_CATEGORY_ID = `${PREFIX}/GET_PRODUCTS_BY_CATEGORY_ID`;
export const GET_PRODUCTS_BY_CATEGORY_ID_START = `${PREFIX}/GET_PRODUCTS_BY_CATEGORY_ID_START`;
export const GET_PRODUCTS_BY_CATEGORY_ID_SUCCESS = `${PREFIX}/GET_PRODUCTS_BY_CATEGORY_ID_SUCCESS`;
export const GET_PRODUCTS_BY_CATEGORY_ID_ERROR = `${PREFIX}/GET_PRODUCTS_BY_CATEGORY_ID_ERROR`;

export const GET_PRODUCT_BY_SKU = `${PREFIX}/GET_PRODUCT_BY_SKU`;
export const GET_PRODUCT_BY_SKU_START = `${PREFIX}/GET_PRODUCT_BY_SKU_START`;
export const GET_PRODUCT_BY_SKU_SUCCESS = `${PREFIX}/GET_PRODUCT_BY_SKU_SUCCESS`;
export const GET_PRODUCT_BY_SKU_ERROR = `${PREFIX}/GET_PRODUCT_BY_SKU_ERROR`;
