export const FETCH_USER_HEALTH_SCORE = '@health/FETCH_USER_HEALTH_SCORE';
export const FETCH_USER_HEALTH_SCORE_SUCCESS =
  '@health/FETCH_USER_HEALTH_SCORE_SUCCESS';
export const FETCH_USER_HEALTH_SCORE_ERROR =
  '@health/FETCH_USER_HEALTH_SCORE_ERROR';
export const FETCH_USER_HEALTH_SCORE_START =
  '@health/FETCH_USER_HEALTH_SCORE_START';

export const FETCH_USER_HEALTH_SCORE_HISTORY =
  '@health/FETCH_USER_HEALTH_SCORE_HISTORY';
export const FETCH_USER_HEALTH_SCORE_HISTORY_SUCCESS =
  '@health/FETCH_USER_HEALTH_SCORE_HISTORY_SUCCESS';
export const FETCH_USER_HEALTH_SCORE_HISTORY_ERROR =
  '@health/FETCH_USER_HEALTH_SCORE_HISTORY_ERROR';
export const FETCH_USER_HEALTH_SCORE_HISTORY_START =
  '@health/FETCH_USER_HEALTH_SCORE_HISTORY_START';

export const FETCH_USER_LIFESTYLE_RESPONSE =
  '@health/FETCH_USER_LIFESTYLE_RESPONSE';
export const FETCH_USER_LIFESTYLE_RESPONSE_SUCCESS =
  '@health/FETCH_USER_LIFESTYLE_RESPONSE_SUCCESS';
export const FETCH_USER_LIFESTYLE_RESPONSE_ERROR =
  '@health/FETCH_USER_LIFESTYLE_RESPONSE_ERROR';
export const FETCH_USER_LIFESTYLE_RESPONSE_START =
  '@health/FETCH_USER_LIFESTYLE_RESPONSE_START';
export const FETCH_USER_LIFESTYLE_RESPONSE_END =
  '@health/FETCH_USER_LIFESTYLE_RESPONSE_END';

export const SUBMIT_USER_LIFESTYLE_RESPONSE =
  '@health/SUBMIT_USER_LIFESTYLE_RESPONSE';
export const SUBMIT_USER_LIFESTYLE_RESPONSE_START =
  '@health/SUBMIT_USER_LIFESTYLE_RESPONSE_START';
export const SUBMIT_USER_LIFESTYLE_RESPONSE_SUCCESS =
  '@health/SUBMIT_USER_LIFESTYLE_RESPONSE_SUCCESS';
export const SUBMIT_USER_LIFESTYLE_RESPONSE_ERROR =
  '@health/SUBMIT_USER_LIFESTYLE_RESPONSE_ERROR';

export const FETCH_USER_LIFESTYLE_RESULTS =
  '@health/FETCH_USER_LIFESTYLE_RESULTS';
export const FETCH_USER_LIFESTYLE_RESULTS_START =
  '@health/FETCH_USER_LIFESTYLE_RESULTS_START';
export const FETCH_USER_LIFESTYLE_RESULTS_SUCCESS =
  '@health/FETCH_USER_LIFESTYLE_RESULTS_SUCCESS';
export const FETCH_USER_LIFESTYLE_RESULTS_ERROR =
  '@health/FETCH_USER_LIFESTYLE_RESULTS_ERROR';

export const FETCH_LIFESTYLE_TIPS = '@health/FETCH_LIFESTYLE_TIPS';
export const FETCH_LIFESTYLE_TIPS_START = '@health/FETCH_LIFESTYLE_TIPS_START';
export const FETCH_LIFESTYLE_TIPS_SUCCESS =
  '@health/FETCH_LIFESTYLE_TIPS_SUCCESS';
export const FETCH_LIFESTYLE_TIPS_ERROR = '@health/FETCH_LIFESTYLE_TIPS_ERROR';

export const FETCH_USER_FACEAGING_RESULTS =
  '@health/FETCH_USER_FACEAGING_RESULTS';
export const FETCH_USER_FACEAGING_RESULTS_START =
  '@health/FETCH_USER_FACEAGING_RESULTS_START';
export const FETCH_USER_FACEAGING_RESULTS_SUCCESS =
  '@health/FETCH_USER_FACEAGING_RESULTS_SUCCESS';
export const FETCH_USER_FACEAGING_RESULTS_ERROR =
  '@health/FETCH_USER_FACEAGING_RESULTS_ERROR';

export const FETCH_USER_FACEAGING_RESULT_IMAGE =
  '@health/FETCH_USER_FACEAGING_RESULT_IMAGE';
export const FETCH_USER_FACEAGING_RESULT_IMAGE_START =
  '@health/FETCH_USER_FACEAGING_RESULT_IMAGE_START';
export const FETCH_USER_FACEAGING_RESULT_IMAGE_SUCCESS =
  '@health/FETCH_USER_FACEAGING_RESULT_IMAGE_SUCCESS';
export const FETCH_USER_FACEAGING_RESULT_IMAGE_ERROR =
  '@health/FETCH_USER_FACEAGING_RESULT_IMAGE_ERROR';

export const RESET_LOADER = '@health/RESET_LOADER';
export const UPLOAD_FACE_IMAGE_START = '@health/UPLOAD_FACE_IMAGE_START';
export const UPLOAD_FACE_IMAGE_SUCCESS = '@health/UPLOAD_FACE_IMAGE_SUCCESS';
export const UPLOAD_FACE_IMAGE_ERROR = '@health/UPLOAD_FACE_IMAGE_ERROR';
export const UPLOAD_FACE_IMAGE = '@health/UPLOAD_FACE_IMAGE';
export const DOWNLOAD_FACE_IMAGE = '@health/DOWNLOAD_FACE_IMAGE';
export const DOWNLOAD_FACE_IMAGE_START = '@health/DOWNLOAD_FACE_IMAGE_START';
export const DOWNLOAD_FACE_IMAGE_SUCCESS =
  '@health/DOWNLOAD_FACE_IMAGE_SUCCESS';
export const DOWNLOAD_FACE_IMAGE_ERROR = '@health/DOWNLOAD_FACE_IMAGE_ERROR';
export const DELETE_FACE_IMAGE_ERROR = '@health/DELETE_FACE_IMAGE_ERROR';
export const DELETE_FACE_IMAGE = '@health/DELETE_FACE_IMAGE';
export const DELETE_FACE_IMAGE_START = '@health/DELETE_FACE_IMAGE_START';
export const DELETE_FACE_IMAGE_SUCCESS = '@health/DELETE_FACE_IMAGE_SUCCESS';

export const FETCH_PRODUCT_RECOMMENDATIONS =
  '@health/FETCH_PRODUCT_RECOMMENDATIONS';
export const FETCH_PRODUCT_RECOMMENDATIONS_START =
  '@health/FETCH_PRODUCT_RECOMMENDATIONS_START';
export const FETCH_PRODUCT_RECOMMENDATIONS_SUCCESS =
  '@health/FETCH_PRODUCT_RECOMMENDATIONS_SUCCESS';
export const FETCH_PRODUCT_RECOMMENDATIONS_ERROR =
  '@health/FETCH_PRODUCT_RECOMMENDATIONS_ERROR';

export const FETCH_PRODUCT_RECOMMENDATIONS_FOR_TIPS =
  '@health/FETCH_PRODUCT_RECOMMENDATIONS_FOR_TIPS';
export const FETCH_PRODUCT_RECOMMENDATIONS_FOR_TIPS_START =
  '@health/FETCH_PRODUCT_RECOMMENDATIONS_FOR_TIPS_START';
export const FETCH_PRODUCT_RECOMMENDATIONS_FOR_TIPS_SUCCESS =
  '@health/FETCH_PRODUCT_RECOMMENDATIONS_FOR_TIPS_SUCCESS';
export const FETCH_PRODUCT_RECOMMENDATIONS_FOR_TIPS_ERROR =
  '@health/FETCH_PRODUCT_RECOMMENDATIONS_FOR_TIPS_ERROR';

export const SET_SUBMIT_LIFESTYLE_FORM_COUNT =
  '@health/SET_SUBMIT_LIFESTYLE_FORM_COUNT';

export const FETCH_USER_HEALTH_RESPONSE = '@health/FETCH_USER_HEALTH_RESPONSE';
export const FETCH_USER_HEALTH_RESPONSE_START =
  '@health/FETCH_USER_HEALTH_RESPONSE_START';
export const FETCH_USER_HEALTH_RESPONSE_SUCCESS =
  '@health/FETCH_USER_HEALTH_RESPONSE_SUCCESS';
export const FETCH_USER_HEALTH_RESPONSE_ERROR =
  '@health/FETCH_USER_HEALTH_RESPONSE_ERROR';

export const SUBMIT_USER_HEALTH_RESPONSE =
  '@health/SUBMIT_USER_HEALTH_RESPONSE';
export const SUBMIT_USER_HEALTH_RESPONSE_START =
  '@health/SUBMIT_USER_HEALTH_RESPONSE_START';
export const SUBMIT_USER_HEALTH_RESPONSE_SUCCESS =
  '@health/SUBMIT_USER_HEALTH_RESPONSE_SUCCESS';
export const SUBMIT_USER_HEALTH_RESPONSE_ERROR =
  '@health/SUBMIT_USER_HEALTH_RESPONSE_ERROR';

export const FETCH_USER_HEALTH_RESULTS = '@health/FETCH_USER_HEALTH_RESULTS';
export const FETCH_USER_HEALTH_RESULTS_START =
  '@health/FETCH_USER_HEALTH_RESULTS_START';
export const FETCH_USER_HEALTH_RESULTS_ERROR =
  '@health/FETCH_USER_HEALTH_RESULTS_ERROR';
export const FETCH_USER_HEALTH_RESULTS_SUCCESS =
  '@health/FETCH_USER_HEALTH_RESULTS_SUCCESS';
