const CLAIM_STATUS = {
  PENDING: 'PENDING' /* TODO : Remove if confirmed */,
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PROCESSING: 'PROCESSING',
  HISTORY: 'HISTORY',
  REQUEST_FOR_INFORMATION: 'REQUEST FOR INFORMATION',
};

export { CLAIM_STATUS };
