export const GET_CLAIM = '@claim/GET_CLAIM';
export const GET_CLAIM_START = '@claim/GET_CLAIM_START';
export const GET_CLAIM_SUCCESS = '@claim/GET_CLAIM_SUCCESS';
export const GET_CLAIM_ERROR = '@claim/GET_CLAIM_ERROR';

export const GET_CLAIMS = '@claim/GET_CLAIMS';
export const GET_CLAIMS_START = '@claim/GET_CLAIMS_START';
export const GET_CLAIMS_SUCCESS = '@claim/GET_CLAIMS_SUCCESS';
export const GET_CLAIMS_ERROR = '@claim/GET_CLAIMS_ERROR';

export const SUBMIT_CLAIM = '@claim/SUBMIT_CLAIM';
export const SUBMIT_CLAIM_START = '@claim/SUBMIT_CLAIM_START';
export const SUBMIT_CLAIM_SUCCESS = '@claim/SUBMIT_CLAIM_SUCCESS';
export const SUBMIT_CLAIM_ERROR = '@claim/SUBMIT_CLAIM_ERROR';

export const GET_CLAIM_FILTERS = '@claim/GET_CLAIM_FILTERS';
export const GET_CLAIM_FILTERS_START = '@claim/GET_CLAIM_FILTERS_START';
export const GET_CLAIM_FILTERS_SUCCESS = '@claim/GET_CLAIM_FILTERS_SUCCESS';
export const GET_CLAIM_FILTERS_ERROR = '@claim/GET_CLAIM_FILTERS_ERROR';

export const UPDATE_CLAIM_FILTERS = '@claim/UPDATE_CLAIM_FILTERS';

export const UPLOAD_DOCUMENTS_FOR_REFERENCE =
  '@claim/UPLOAD_DOCUMENTS_FOR_REFERENCE';
export const UPLOAD_DOCUMENTS_FOR_REFERENCE_START =
  '@claim/UPLOAD_DOCUMENTS_FOR_REFERENCE_START';
export const UPLOAD_DOCUMENTS_FOR_REFERENCE_ERROR =
  '@claim/UPLOAD_DOCUMENTS_FOR_REFERENCE_ERROR';
export const UPLOAD_DOCUMENTS_FOR_REFERENCE_SUCCESS =
  '@claim/UPLOAD_DOCUMENTS_FOR_REFERENCE_SUCCESS';
